{ pkgs }:
[
  pkgs.bottom
  pkgs.bun
  pkgs.ccache
  pkgs.cloudflared
  pkgs.cmake
  pkgs.cmake-format
  pkgs.code-cursor
  pkgs.curlFull
  pkgs.fd
  pkgs.gh
  pkgs.gnumake
  pkgs.go
  pkgs.hyperfine
  pkgs.jq
  pkgs.jujutsu
  pkgs.kind
  pkgs.luarocks
  pkgs.ninja
  pkgs.nodejs_26
  pkgs.opam
  (pkgs.pnpm_11.override { nodejs-slim = pkgs.nodejs-slim_26; })
  pkgs.python313
  pkgs.qemu
  pkgs.ripgrep
  pkgs.rustup
  pkgs.tex-fmt
  pkgs.texliveFull
  pkgs.tree-sitter
  pkgs.uv
  pkgs.wget
  pkgs.zig
]
